services:
  web:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file: .env

  worker:
    build: ./backend
    command: celery -A app.tasks worker --loglevel=info --uid=nobody --gid=nogroup # --max-tasks-per-child=10
    deploy:
        replicas: 2 # Just 2 for this presentation
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      - redis
    env_file: .env

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
